/**
 * Markdown Templates
 * Contains all markdown formatting templates
 */

/**
 * Main markdown template for a submission
 * Minimalist, elegant design
 *
 * @param title - Problem title
 * @param problemUrl - LeetCode problem URL
 * @param difficulty - Problem difficulty (Easy, Medium, Hard)
 * @param topics - Array of topic names
 * @param language - Programming language
 * @param runtime - Runtime in milliseconds
 * @param runtimePercentile - Runtime percentile
 * @param memory - Memory in bytes
 * @param memoryPercentile - Memory percentile
 * @param submissionDate - Submission date string
 * @param code - Solution code
 * @param languageFence - Language identifier for code fence
 * @returns Complete markdown document
 */
export function submissionTemplate(
  title: string,
  problemUrl: string,
  difficulty: string,
  topics: string[],
  language: string,
  runtime: number,
  runtimePercentile: number | undefined,
  memory: number,
  memoryPercentile: number | undefined,
  submissionDate: string,
  code: string,
  languageFence: string
): string {
  const topicList = topics.length > 0 ? topics.join(' · ') : 'None';
  const runtimePercent = runtimePercentile !== undefined ? ` (${runtimePercentile.toFixed(2)}%)` : '';
  const memoryMB = (memory / (1024 * 1024)).toFixed(1);
  const memoryPercent = memoryPercentile !== undefined ? ` (${memoryPercentile.toFixed(2)}%)` : '';
  
  return `# ${title}

[Problem Link](${problemUrl})

## Details

**Difficulty:** ${difficulty}  
**Topics:** ${topicList}

## Submission

**Language:** ${language}  
**Runtime:** ${runtime} ms${runtimePercent}  
**Memory:** ${memoryMB} MB${memoryPercent}  
**Submitted:** ${submissionDate}

## Solution

\`\`\`${languageFence}
${code}
\`\`\`

---

*Generated by [DevGrid](https://github.com/yourusername/devgrid)*
`;
}
