/**
 * Markdown Templates
 * Contains all markdown formatting templates
 */

/**
 * Main markdown template for a submission
 * Minimalist, elegant design with full problem details
 *
 * @param title - Problem title
 * @param problemUrl - LeetCode problem URL
 * @param difficulty - Problem difficulty (Easy, Medium, Hard)
 * @param topics - Array of topic names
 * @param language - Programming language
 * @param runtime - Runtime in milliseconds
 * @param runtimePercentile - Runtime percentile
 * @param memory - Memory in bytes
 * @param memoryPercentile - Memory percentile
 * @param submissionDate - Submission date string
 * @param code - Solution code
 * @param languageFence - Language identifier for code fence
 * @param description - Problem description (optional)
 * @param examples - Problem examples (optional)
 * @param constraints - Problem constraints (optional)
 * @returns Complete markdown document
 */
export function submissionTemplate(
  title: string,
  problemUrl: string,
  difficulty: string,
  topics: string[],
  language: string,
  runtime: number,
  runtimePercentile: number | undefined,
  memory: number,
  memoryPercentile: number | undefined,
  submissionDate: string,
  code: string,
  languageFence: string,
  description?: string,
  examples?: string[],
  constraints?: string[]
): string {
  const runtimePercent = runtimePercentile !== undefined ? ` (${runtimePercentile.toFixed(2)}%)` : '';
  const memoryMB = (memory / (1024 * 1024)).toFixed(1);
  const memoryPercent = memoryPercentile !== undefined ? ` (${memoryPercentile.toFixed(2)}%)` : '';
  
  // Only include Topics section if topics exist
  const topicsSection = topics.length > 0 
    ? `**Topics:** ${topics.join(' · ')}  \n` 
    : '';
  
  // Build problem section if description exists
  let problemSection = '';
  if (description && description.length > 0) {
    problemSection = `\n## Problem\n\n${description}\n`;
  }
  
  // Build examples section if examples exist
  let examplesSection = '';
  if (examples && examples.length > 0) {
    examplesSection = '\n## Examples\n\n';
    examples.forEach((example, index) => {
      examplesSection += `### Example ${index + 1}\n\n\`\`\`\n${example}\n\`\`\`\n\n`;
    });
  }
  
  // Build constraints section if constraints exist
  let constraintsSection = '';
  if (constraints && constraints.length > 0) {
    constraintsSection = '\n## Constraints\n\n';
    constraints.forEach(constraint => {
      constraintsSection += `- ${constraint}\n`;
    });
    constraintsSection += '\n';
  }
  
  return `# ${title}

[Problem Link](${problemUrl})

## Details

**Difficulty:** ${difficulty}  
${topicsSection}${problemSection}${examplesSection}${constraintsSection}
## Submission

**Language:** ${language}  
**Runtime:** ${runtime} ms${runtimePercent}  
**Memory:** ${memoryMB} MB${memoryPercent}  
**Submitted:** ${submissionDate}

## Solution

\`\`\`${languageFence}
${code}
\`\`\`

---

*Generated by [DevGrid](https://github.com/yourusername/devgrid)*
`;
}
